### ISSUE TITLE
Don't default to all black when printing layout cards with color

### ISSUE THREAD

**Issue by EvyBongers** [keyboardio/Chrysalis#1160]
**Is your feature request related to a problem? Please describe.**
For any key that I assigned a non-default color, I want those printed, but wouldn't want to see the other ones black. Currently that's only possible by setting the color to white, which means a lot of backlight (ref: #1128).

**Describe the solution you'd like**
I'd like to have an option to only print non-black keys in color.

**Describe alternatives you've considered**
My initial ideas (as mentioned on Discord):
- add a (default?) option to not print rgb `#000000`
- add a possibility for color transparent/none (as already mentioned by @algernon on Discord, this concept isn't supported by Chrysalis and Kaleidoscope)

Another alternative I came up with later:
- rather than painting the keys, paint the border around it (and possibly characters), which would look more like backlight.

**Additional context**
N/A

**Comment by noerw** [comment]
this is not a proper fix for the reasons outlined above and in https://github.com/keyboardio/Chrysalis/pull/1128#issuecomment-1264317935, but for a quick solution, add this style (in app via dev console, or append to `src/styles/keymap.css`):
```css
@media print {
  svg.layer .key > ellipse[fill="rgb(0, 0, 0)"],
  svg.layer .key > path[fill="rgb(0, 0, 0)"] {
    fill: transparent;
  }

  svg.layer .key > ellipse[fill="rgb(0, 0, 0)"] ~ g text,
  svg.layer .key > path[fill="rgb(0, 0, 0)"] ~ g text {
    fill: #000;
  }
}
```
